version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - COMPOSE_HTTP_TIMEOUT=200
      - DOCKER_CLIENT_TIMEOUT=200
    restart: always
    command: npm run dev 